stages:
  prepro:
    cmd: python src/preprocess.py data/data.csv data/clean_data.csv params.yaml
    deps:
    - data/data.csv
    - params.yaml
    outs:
    - data/clean_data.csv
  transform:
    cmd: python src/transform.py data/clean_data.csv data/transformed_data.csv params.yaml
    deps:
    - data/clean_data.csv
    - params.yaml
    outs:
    - data/transformed_data.csv
  featureEngineer:
    cmd: python src/feature_engineer.py data/transformed_data.csv data/top_features.csv
      params.yaml
    deps:
    - data/transformed_data.csv
    - params.yaml
    outs:
    - data/top_features.csv
