train:
  TEST_SIZE: 0.3
  VALIDATE_SIZE: 0.2
  RANDOM_STATE: 2024
  CV: 5
  alpha: 0.1
preprocessing:
  target: price
  features:
  - area
  - bedrooms
  - bathrooms
  - stories
  - parking
  - furnishingstatus
continuas:
- area
- price
discretas:
- bedrooms
- bathrooms
- stories
- parking
categoricas:
- furnishingstatus
