train:
  TEST_SIZE: 0.3
  VALIDATE_SIZE: 0.2
  RANDOM_STATE: 2024
  CV: 5
  alpha: 0.1
preprocessing:
  target: price
  features:
  - area
  - bedrooms
  - bathrooms
  - stories
  - mainroad
  - guestroom
  - basement
  - hotwaterheating
  - airconditioning
  - parking
  - prefarea
  - furnishingstatus
continuas:
- area
discretas:
- bedrooms
- bathrooms
- stories
- parking
categoricas:
- mainroad
- guestroom
- basement
- hotwaterheating
- airconditioning
- prefarea
- furnishingstatus
optuna:
  RandomForest:
    n_estimators: 185
    max_depth: 15
    min_samples_split: 2
  GradientBoosting:
    learning_rate: 0.2717814133962777
    n_estimators: 77
    max_depth: 3
optimization:
  RandomForest:
    n_estimators: 200
    min_samples_split: 10
    max_depth: null
  GradientBoosting:
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.2
  LinearRegression:
    fit_intercept: false
